[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-8_x']

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]
cmds = ['cd backend && npm run migrate || true']

[start]
cmd = 'cd backend && npm start'

